(dp1
S'output'
p2
S'<type \'exceptions.SyntaxError\'> Field: invalid table name: provas-d, use rname for "funny" names'
p3
sS'layer'
p4
S'C:\\Users\\Bruno\\Downloads\\web2py\\applications\\avalweb3\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 03EE4C80, file "C:\\Users\\Bruno\\Downloads\\web2py\\applications\\avalweb3\\models\\db.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Bruno\\Downloads\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\Bruno\\Downloads\\web2py\\applications\\avalweb3\\models\\db.py", line 77, in <module>\n    primarykey=[\'cod_prova\']\n  File "C:\\Users\\Bruno\\Downloads\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 587, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "C:\\Users\\Bruno\\Downloads\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 599, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "C:\\Users\\Bruno\\Downloads\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 230, in __init__\n    \'use rname for "funny" names\' % tablename)\nSyntaxError: Field: invalid table name: provas-d, use rname for "funny" names\n'
p11
s.